### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by MavMMSZ** [MavMMSZ/Prework-Study-Guide#3]
# JavaScript

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I an easily find and read the information

## Acceptance Criteria
GIVEN a prework study guide
WHEN I view the study guide
THEN I an see the four topics I learned listed along with a suggestion on what I should study first

**Comment by AvinashMarkad** [comment]
To address this user story, you can create a simple webpage to display the prework study guide. The page will list four topics and provide a suggestion on what to study first. We can use HTML, CSS, and JavaScript to structure and style the page, and to dynamically display the suggested topic.

Here's a basic implementation:

### 1. HTML (Structure)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prework Study Guide</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Prework Study Guide</h1>
    </header>
    <main>
        <section>
            <h2>Topics Covered</h2>
            <ul id="topics-list">
                <li>HTML</li>
                <li>CSS</li>
                <li>JavaScript</li>
                <li>Git</li>
            </ul>
        </section>
        <section id="study-suggestion">
            <h2>What to Study First</h2>
            <p id="suggestion-text">Please select a topic to get started.</p>
        </section>
    </main>
    <script src="script.js"></script>
</body>
</html>
```

### 2. CSS (Styling)
```css
/* styles.css */
body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
}

header {
    background: #333;
    color: #fff;
    padding: 10px 0;
    text-align: center;
}

main {
    padding: 20px;
}

h1, h2 {
    color: #333;
}

ul {
    list-style-type: none;
    padding: 0;
}

li {
    background: #fff;
    margin: 10px 0;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    cursor: pointer;
}

li:hover {
    background-color: #f0f0f0;
}

#study-suggestion {
    margin-top: 20px;
}

#suggestion-text {
    font-size: 1.2em;
    color: #333;
}
```

### 3. JavaScript (Functionality)
```javascript
// script.js
document.addEventListener('DOMContentLoaded', () => {
    const topics = ["HTML", "CSS", "JavaScript", "Git"];
    const suggestionText = document.getElementById('suggestion-text');
    const topicsList = document.getElementById('topics-list');

    topics.forEach(topic => {
        const li = document.createElement('li');
        li.textContent = topic;
        li.addEventListener('click', () => {
            suggestTopic(topic);
        });
        topicsList.appendChild(li);
    });

    function suggestTopic(topic) {
        suggestionText.textContent = `You should start by studying ${topic}.`;
    }

    // Initial suggestion
    suggestTopic(topics[0]);
});
```

### Explanation
1. **HTML Structure**:
   - The `header` section contains the title of the study guide.
   - The `main` section includes two parts:
     - A list of topics covered.
     - A section for the study suggestion.

2. **CSS Styling**:
   - Basic styling for the body, header, and main sections.
   - The topics list items have a hover effect to make them interactive.

3. **JavaScript Functionality**:
   - On page load, the script initializes the topics and adds them to the list.
   - When a topic is clicked, the `suggestTopic` function updates the suggestion text with the chosen topic.
   - An initial suggestion is made using the first topic in the list.

This implementation provides a simple yet effective way for students to see the topics covered and get a suggestion on what to study first. You can expand or modify this setup to fit more specific requirements or design preferences.
